#define STRING_SPACE_SEPARATOR " "
#define STRING_LINE_SEPARATOR "\n"
#define STRING_LAYER_SEPARATOR "-"
#define STRING_EQUALS "="
#define STRING_QUOTE "\""

#define STRING_NULL "N"
#define STRING_COLOR_NULL "-1 -1 -1"

#define STRING_HELPERXML_STARTTAG_START "<"
#define STRING_HELPERXML_STARTTAG_END ">"
#define STRING_HELPERXML_ENDTAG_START "</"
#define STRING_HELPERXML_ENDTAG_END ">"

#define STRING_SCENENODE_TAGNAME "SceneNode"
#define STRING_SCENENODE_MODEL_TAGNAME "Model" 
#define STRING_SCENENODE_POSITION_TAGNAME "Position"
#define STRING_SCENENODE_ROTATION_TAGNAME "Rotation"
#define STRING_SCENENODE_SCALE_TAGNAME "Scale"

#define STRING_SCENEMANAGER_TAGNAME "Scene"