#define STRING_SPACE_SEPARATOR " "
#define STRING_LINE_SEPARATOR "\n"
#define STRING_LAYER_SEPARATOR "-"
#define STRING_EQUALS "="
#define STRING_QUOTE "\""

#define STRING_NULL "N"
#define STRING_COLOR_NULL "-1 -1 -1"

#define STRING_HELPERXML_STARTTAG_START "<"
#define STRING_HELPERXML_STARTTAG_END ">"
#define STRING_HELPERXML_ENDTAG_START "</"
#define STRING_HELPERXML_ENDTAG_END ">"